services:
  bluenaas:
    image: bluenaas-svc
    container_name: bluenaas-http-svc
    env_file: "./.env.local"
    command:
      [
        "uvicorn",
        "bluenaas.app:app",
        "--host=0.0.0.0",
        "--port=8000",
        "--reload",
      ]
    environment:
      DEBUG: True
    volumes:
      - ${PWD}/bluenaas:/app/bluenaas
    ports:
      - "8001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
