version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: yes
  botocore:
    level: INFO
    handlers: [console]
    propagate: yes
  urllib3:
    level: INFO
    handlers: [console]
    propagate: yes
  matplotlib:
    level: INFO
    handlers: [console]
    propagate: yes
  bluecellulab:
    level: INFO
    handlers: [console]
    propagate: yes
  charset_normalizer:
    level: INFO
    handlers: [console]
    propagate: yes
root:
  level: INFO
  handlers: [console]
  propagate: yes
