name: Publish develop

on:
    push:
      branches:
        - develop

jobs:
  publish-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t bluebrain/blue-naas-single-cell . --platform=linux/amd64

      - name: Publish To DockerHub
        run: |
          docker push bluebrain/blue-naas-single-cell
